---
  - name: "Update"
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 86400
  
  - name: remove dependencies that are no longer required
    become: true
    apt:
      autoremove: yes

  - name: "upgrade packages"
    become: true
    apt: 
      upgrade: yes

  - name: "extract the zipped artifact into the EC2 instance"
    become: true
    unarchive:
      src: "~/project/build-artifact.tar.gz"
      dest: .


  - name: "start the app"
    become: true
    shell: |
      npm install
      pm2 stop default
      pm2 start npm -- start